name: Snake Animation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: ${{ github.repository_owner }} # Add this if required

      - name: Commit generated snake SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate contribution grid snake"
          file_pattern: "output/github-contribution-grid-snake.svg"
